# Generated by Django 3.2.9 on 2021-12-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_title_announcements_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Announcements',
            new_name='announcements',
        ),
    ]
