# Generated by Django 3.2.9 on 2021-12-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson', verbose_name='Aula'),
        ),
    ]
